CREATE TABLE IF NOT EXISTS ASSOCIADOS (
	ID_ASSOCIADO INT unsigned not null auto_increment,
    NOME_ASSOCIADO varchar(255) not null,
    CPF varchar(11) not null,
    AUTORIZADO char(1) NOT NULL,
    primary key(ID_ASSOCIADO) 
);

CREATE TABLE IF NOT EXISTS PAUTAS (
	ID_PAUTA INT unsigned not null auto_increment,
    NOME_PAUTA varchar(255) not null,
    DESCRICAO_PAUTA varchar(255) not null,
    USER_CRAICAO_ID INT UNSIGNED NOT NULL,
    DATA_CRIACAO date not null,
    SN_SESSAO_VOTO char(1) default 'N',
    USER_CRIACAO_SESSAO_VOTO_ID INT UNSIGNED,
    DATA_INICIO_SESSAO_VOTO DATE,
    DATA_FIM_SESSAO_VOTO DATE,
    primary key(ID_PAUTA),
    FOREIGN KEY(USER_CRAICAO_ID) REFERENCES ASSOCIADO (ID_ASSOCIADO),
    FOREIGN KEY(USER_CRIACAO_SESSAO_VOTO_ID) REFERENCES ASSOCIADO (ID_ASSOCIADO)
    
);

CREATE TABLE IF NOT EXISTS VOTOS (
	ID_VOTO INT unsigned not null auto_increment,
    PAUTA_ID INT UNSIGNED NOT NULL,
    VOTO char(1) not null,
    ASSOCIADO_ID INT UNSIGNED NOT NULL,
    DATA_VOTO date not null,
    primary key(ID_VOTO),
    FOREIGN KEY(PAUTA_ID) REFERENCES PAUTAS (ID_PAUTA),
    FOREIGN KEY(ASSOCIADO_ID) REFERENCES ASSOCIADO (ID_ASSOCIADO)
    
);